#
# K8sコンポーネント配置に必要なディレクトリを作成
#
- name: Setup Kubernetes Dirs
  hosts:
  - masters
  - nodes
  - proxys
  - storages
  become: true
  tasks:
    - include_tasks: tasks/setup_k8s_dirs.yml

      
- name: Mount NFS server (bootnode)
  hosts: all
  become: true
  tasks:
  - name: Mount up
    mount:
      path: /mnt
      src: bootnode:/srv/k8s
      fstype: nfs
      state: mounted

#
# ワーカーノードのセットアップ
#
- name: Configure work-nodes
  hosts:
  - nodes
  - storages
  - proxys
  gather_facts: true
  become: true
  roles:
    - role: net_bridge
      when: pod_network == "bridge"
    - role: net_flannel
      when: pod_network == "flannel"
    - role: net_calico
      when: pod_network == "calico" 
    - node_worker

#########################################
#
# ノードへロール設定、ノードラベル設定
#
#  flannel使用時にマスターノードへのtaint設定
#  
#
- name: Configure cluster
  hosts:
  - bootnode
  gather_facts: true
  become: true
  tasks:
    - include_vars:
        dir: vars
    - include_tasks: tasks/role_worker.yaml
    - include_tasks: tasks/add-node-label.yaml
  roles:
    - role: net_calico
      when: pod_network == "calico"      
      
