#
# create certs for new "edge node" as worker node
# 
#  1. edit nodes name and node_ip
#  2. do following command
#      ansible-playbook -i hosts_k8s playbook/install_new_node.yml
#
- name: Create kubeconfig for new nodes
  vars:
    nodes:
      - { name: 'raspi07' , node_ip: '192.168.1.241' }
  hosts:
  - bootnode
  roles:
    - create_kubeconfig

#- name: copy cert files
#  hosts:
#  - raspi07
#  tasks:
#  - copy:
#      src: "{{ r_ca_home2 }}/ca.pem"
#      dest: /etc/kubernetes/pki/ca.pem
#      owner: root
#      group: root
#      mode: '0600'
#      remote_src: yes
