#
# K8sコンポーネント配置に必要なディレクトリを作成
#
- name: Setup Kubernetes Dirs
  hosts:
  - masters
  - nodes
  - proxys
  - storages
  become: true
  tasks:
    - include_tasks: tasks/setup_k8s_dirs.yml

#
# 証明書をbootnodeのNFSサーバー上に準備
#
- name: Download a containerd on NFS server
  hosts:
  - bootnode
  roles:
    - cert_setup

#
# マスターノードのための内部ロードバランサーの起動
#
- name: Internal HA-PROXY install
  hosts:
  - mlbs
  vars:
    lb_pos: "Internal"
  gather_facts: true
  become: true
  become_user: root
  become_method: sudo
  roles:
    - haproxy
    - keepalived


#
# 外部ロードバランサーの起動
#   クラウドサービスのロードバランサーのサービス相当
#
- name: External HA-PROXY install
  hosts:
  - elbs
  vars:
    lb_pos: "Frontend"
  gather_facts: true
  become: true
  become_user: root
  become_method: sudo
  roles:
    - haproxy
    - keepalived

# 
# etcd クラスタとマスターノードのセットアップ
#   etcdサーバーはマスターノード上に配置
#   クラスタネットワークすなわちノード間通信の選択により設定が変わる
#     * 仮想環境の専用ネットワークをブリッジで繋ぐ方法 
#     * flannelでオーバーレイで繋ぐ方法
#
- name: Configure etcd on masters
  hosts:
  - masters
  gather_facts: true
  become: true
  roles:
    - etcd
    - node_master
    - role: node_worker
      when: pod_network == "flannel"
    - role: net_flannel
      when: pod_network == "flannel"      
    - role: net_bridge
      when: pod_network == "bridge"

# 
#  RBAC for Kubelet Authorization
#
- name: Configure RBAC
  hosts:
  - bootnode
  gather_facts: true
  become: true
  become_user: vagrant
  tasks:
    - include_tasks: tasks/config_rbac_kubelet.yml

#
# ワーカーノードのセットアップ
#
- name: Configure work-nodes
  hosts:
  - nodes
  - storages
  - proxys
  gather_facts: true
  become: true
  roles:
    - node_worker
    - role: net_bridge
      when: pod_network == "bridge"
    - role: net_flannel
      when: pod_network == "flannel"      

#########################################
#
# ノードへロール設定
#
#  flannel使用時にマスターノードへのtaint設定
#  
#
- name: Configure work-nodes
  hosts:
  - bootnode
  gather_facts: true
  become: true
  tasks:
    - include_vars:
        dir: vars
    - include_tasks: tasks/role_master.yaml
      when:
      - pod_network == "flannel"
#    - wait_for:  残骸と思うので暫定コメント
#        timeout: 60
    - include_tasks: tasks/role_worker.yaml

#########################################
#
# プロキシノードのコンテナランタイム初期化
#   cni0が起動していないと、kube-proxyが
#   動作しないためにコンテナを起動して
#　 初期化を促す
- name: test proxy-nodes
  hosts:
  - proxys    
  gather_facts: true
  become: true
  tasks:
    - include_tasks: tasks/proxy_test.yaml

#########################################

#
# ストレージノードのセットアップ
#
- name: Setup Kubernetes Dirs
  hosts:
  - storages
  become: true
  tasks:
    - name: Git Repositorys Create a ext4 filesystem on /dev/sdc and check disk blocks
      filesystem:
        fstype: ext4
        dev: /dev/sdc
    - name: Mount up device by /dev/sdb
      mount:
        path: /var/lib/rook
        src:  /dev/sdc
        fstype: ext4
        state: mounted

- name: Setup Kubernetes Dirs
  hosts:
  - bootnode
  tasks:
    - include_tasks: tasks/role_storage.yaml
      when:
      - storage_node == "true"

#
# 不要のマニフェストのクリーンナップ
#
- name: delete file
  hosts:
  - proxys    
  gather_facts: true
  become: true
  tasks:
    - include_tasks: tasks/proxy_del_manifest.yaml

#
# モニタリングセットアップ
# CoreDNSセットアップ
#
- name: K8s Monitoring setup
  hosts: bootnode
  gather_facts: true
  become: true
  roles:
    - addon_coredns
    - addon_metrics-server
    - addon_dashboard


      

