#
# K8sコンポーネント配置に必要なディレクトリを作成
#
- name: Setup Kubernetes Dirs
  hosts:
  - masters
  - nodes
  - proxys
  - storages
  - elbs
  become: true
  tasks:
    - include_tasks: tasks/setup_k8s_dirs.yml

#
# 証明書をbootnodeのNFSサーバー上に準備
#
- name: Download software packeges
  hosts:
  - bootnode
  become: true  
  roles:
    - bootnode    
    - cert_setup

- name: Mount NFS server (bootnode)
  hosts: all
  become: true
  tasks:
  - name: Mount up
    mount:
      path: /mnt
      src: bootnode:/srv/k8s
      fstype: nfs
      state: mounted
    
#
# マスターノードのための内部ロードバランサーの起動
#
- name: Internal HA-PROXY install
  hosts:
  - mlbs
  vars:
    lb_pos: "Internal"
  gather_facts: true
  become: true
  become_user: root
  become_method: sudo
  roles:
    - haproxy
    - keepalived

#
# 外部ロードバランサーの起動
#   クラウドサービスのロードバランサーのサービス相当
#
- name: External HA-PROXY install
  hosts:
  - elbs
  vars:
    lb_pos: "Frontend"
  gather_facts: true
  become: true
  become_user: root
  become_method: sudo
  roles:
    - haproxy
    - keepalived

# 
# etcd クラスタとマスターノードのセットアップ
#   etcdサーバーはマスターノード上に配置
#   クラスタネットワークすなわちノード間通信の選択により設定が変わる
#     * 仮想環境の専用ネットワークをブリッジで繋ぐ方法 
#     * flannelでオーバーレイで繋ぐ方法
#
- name: Configure etcd on masters
  hosts:
  - masters
  gather_facts: true
  become: true
  roles:
    - etcd
    - node_master
    - role: node_worker
      when: pod_network == "flannel" or pod_network == "calico"
    - role: net_bridge
      when: pod_network == "bridge"
    - role: net_flannel
      when: pod_network == "flannel"
  tasks:
    - include_tasks: tasks/kubeconfig_setup.yml
      
# 
#  RBAC for Kubelet Authorization
#
- name: Configure RBAC
  hosts:
  - bootnode
  gather_facts: true
  become: true
  become_user: vagrant
  tasks:
    # 処理完了まで時間を取らないと失敗する
    - wait_for:
        timeout: 100
    - include_tasks: tasks/config_rbac_kubelet.yml
    - include_tasks: tasks/kubeconfig_setup.yml

#
# ワーカーノードのセットアップ
#
- name: Configure work-nodes
  hosts:
  - nodes
  - storages
  - proxys
  - elbs
  gather_facts: true
  become: true
  roles:
    - node_worker    
    - role: net_bridge
      when: pod_network == "bridge"
    - role: net_flannel
      when: pod_network == "flannel"
      
#
# ノードへロール設定、ノードラベル設定
# マスターノードへのtaint設定
#
- name: Configure cluster
  hosts:
  - bootnode
  gather_facts: true
  become: true
  tasks:
    # ノードのリスト読み込み
    - include_vars:
        dir: vars
    #  flannel使用時にマスターノードへのtaint設定
    - include_tasks: tasks/role_master.yaml
      when:
      - pod_network == "flannel" or pod_network == "calico"
    # 残骸ではなく、Waitがないと、次のコマンドが失敗する
    - wait_for:
        timeout: 20
    # ワーカーノードにロール設定
    - include_tasks: tasks/role_worker.yaml
    #- include_tasks: tasks/add-node-label.yaml
  roles:
    # Calicoマニフェストデプロイ
    - role: net_calico
      when: pod_network == "calico"      
      

# プロキシノードのコンテナランタイム初期化
#   cni0が起動していないと、kube-proxyが
#   動作しないためにコンテナを起動して
#　 初期化を促す
- name: test proxy-nodes
  hosts:
  - proxys
  - elbs
  gather_facts: true
  become: true
  tasks:
    - include_tasks: tasks/proxy_test.yaml

- name: Setup a role of the storage node 
  hosts:
  - bootnode
  tasks:
    - include_tasks: tasks/role_storage.yaml
      when:
      - storage_node == "true"

#
# 不要のマニフェストのクリーンナップ
#
- name: delete file
  hosts:
  - proxys
  - elbs
  gather_facts: true
  become: true
  tasks:
    - include_tasks: tasks/proxy_del_manifest.yaml

#
# モニタリングセットアップ
# CoreDNSセットアップ
#
- name: K8s Monitoring setup
  hosts: bootnode
  gather_facts: true
  become: true
  #tasks:
  #  - wait_for:
  #      timeout: 30
  roles:
    - addon_coredns
    - addon_metrics-server
    - addon_dashboard

#
# Ingress コントローラーとHA-Proxyの設定
#
- name: Deploy kube-keepalived-vip + ingress 
  hosts:
  - bootnode
  gather_facts: true
  become: true
  tasks:
    - debug: msg="proxy_node = {{ proxy_node }}"
    - include_tasks: tasks/deploy-ka-vip-ingress.yaml
      when:
      - proxy_node == "true"
    - debug: msg="export KUBECONFIG=`pwd`/kubeconfig"

      
