#
# ストレージ用ノードにROOK/Ceph用ボリュームをマウントする
#
# 適用方法
# ansible-playbook -i hosts_k8s playbook/setup_storage.yml
#
# vagrant@bootnode:/vagrant$ ssh node5 lsblk
# NAME   MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
# sda      8:0    0  10G  0 disk 
# └─sda1   8:1    0  10G  0 part /
# sdb      8:16   0  10M  0 disk 
# sdc      8:32   0  40G  0 disk 
#
#
# vagrant@bootnode:/vagrant$ ssh node5 lsblk
# NAME   MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
# sda      8:0    0  10G  0 disk 
# └─sda1   8:1    0  10G  0 part /
# sdb      8:16   0  10M  0 disk 
# sdc      8:32   0  40G  0 disk /var/lib/rook
#


- name: Setup Kubernetes Dirs
  hosts:
  - node5
  - node6
  - node7
  become: true
  
  tasks:
    - name: Git Repositorys Create a ext4 filesystem on /dev/sdc and check disk blocks
      filesystem:
        fstype: ext4
        dev: /dev/sdc

    - name: Mount up device by /dev/sdb
      mount:
        path: /var/lib/rook
        src:  /dev/sdc
        fstype: ext4
        state: mounted

- name: Setup Kubernetes Dirs
  hosts:
  - bootnode
  tasks:
  - include_tasks: tasks/role_storage.yaml
