---
- name: config boot node
  hosts: bootnode
  gather_facts: true
  become: true
  roles:
  - bootnode

- name: config master & worker node
  hosts: all
  gather_facts: true
  become: true
  roles:
  - base_linux

#
# 証明書をbootnodeのNFSサーバー上に準備
#
- name: Download a containerd on NFS server
  hosts:
  - bootnode
  roles:
    - cert_setup

  

  
