#
# テスト用
#

#
# モニタリングセットアップ
# CoreDNSセットアップ
#
#- name: K8s Monitoring setup
#  hosts: masters
#  gather_facts: true
#  become: true
#  roles:
#    - addon_helm3     
#    - addon_coredns
#    - addon_metrics-server
#    - addon_dashboard
#  tasks:
#    - debug: msg="export KUBECONFIG=`pwd`/kubeconfig"


- name: TEST Internal HA-PROXY install
  hosts:
  - bootnode
  - mlbs
  vars:
    lb_pos: "Internal"
  gather_facts: true
  become: true
  become_user: root
  become_method: sudo
  roles:
    - keepalived

- name: External HA-PROXY install
  hosts:
  - bootnode  
  - elbs
  vars:
    lb_pos: "Frontend"
  gather_facts: true
  become: true
  become_user: root
  become_method: sudo
  roles:
    - keepalived

