#
# テスト用
#
- name: Deploy addon for k8s
  hosts: bootnode
  gather_facts: yes
  become: yes
  roles:
    - addon_helm3    
    - addon_coredns
    - addon_metrics-server
    - addon_dashboard
    - addon_ingress

