- name: Download a containerd on NFS server
  hosts:
  - bootnode
  tasks:
    - debug: msg="custom_kubernetes = {{ custom_kubernetes }}"
    
    - name: test true
      command: ls
      when: custom_kubernetes == 'true'
      
    - name: test false
      command: ls
      when: custom_kubernetes == "false"

    - name: test no condition
      command: ls

   
    