#
# 内部ロードバランサーの起動
#

- name: Internal HA-PROXY install
  hosts:
  - mlbs
  vars:
    lb_pos: "Internal"
  gather_facts: true
  become: true
  become_user: root
  become_method: sudo
  roles:
    - haproxy
    - keepalived


#
# 外部ロードバランサーの起動
#

- name: External HA-PROXY install
  hosts:
  - elbs
  vars:
    lb_pos: "Frontend"
  gather_facts: true
  become: true
  become_user: root
  become_method: sudo
  roles:
    - haproxy
    - keepalived



