#
# テスト用
#
# 
#  RBAC for Kubelet Authorization
#
- name: Configure RBAC
  hosts:
  - bootnode
  gather_facts: true
  become: true
  #become_user: vagrant
  tasks:
    # RBAC設定を追加
    - include_tasks: tasks/config_rbac_kubelet.yml
    # kubectlコマンドをログインシェルから使えるように設定する      
    - include_tasks: tasks/kubeconfig_setup.yml

