#
# テスト用
#
- name: Deploy addon for k8s
  hosts: bootnode
  gather_facts: true
  become: true
  roles:
    - addon_helm3    
    - addon_coredns
    - addon_metrics-server
    - addon_dashboard
    - addon_ingress

