#
# テスト用タスク
#
- name: test 
  hosts:
  - all 
  gather_facts: true
  become: true
  tasks:
    - debug: msg="proxy_node = {{ proxy_node }}"
    - include_tasks: tasks/test.yaml
      when:
      - proxy_node == "true"
