#
# Docker CE のインストール
#

#
# mkdir directory for cni
#  flannel などのプラグインの設定ファイルが入る
#
- name: start configuration
  file:
    path: /etc/cni/net.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: mkdir /opt/cni/bin/
  file:
    path: /opt/cni/bin/
    state: directory
    owner: root
    group: root
    mode: '0755'

- include_tasks: dl_cni_plugin.yaml
- include_tasks: dl_crictl.yaml

##
## master1 でダウンロードが完了したら、master2以降の待機をリリースする
##
- name: Touch the same file, but add/remove some permissions
  file:
    path: "{{ r_download_dir }}/cni_plugin_start.lock"
    state: touch
    mode: u+rw,g-wx,o-rwx  
  when: ansible_facts.hostname is match("master1")

##
## master1 でダウンロードが完了するまで待つ
##
- name: Wait until the lock file is removed
  wait_for:
    path: "{{ r_download_dir }}/cni_plugin_start.lock"
    state: present
  
- name: Configure CNI Networking
  unarchive:
    src: "{{ r_download_dir }}/cni-plugins-linux-amd64-{{ cni_plugins }}.tgz"
    dest: /opt/cni/bin/
    owner: root
    group: root
    mode: '0755'

  
- name: Install a list of packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - nfs-common

- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

- name: Install docker-ce {{ docker_version }}
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - docker-ce={{ docker_version }}
    - docker-ce-cli={{ docker_version }}
    - containerd.io
    
