#
# セッションとホスト名を表示する
#
apiVersion: v1
kind: Service
metadata:
  name: webserver2
spec:
  type: NodePort
  selector:
    app: webserver2
  ports:
    - port: 9080
      targetPort: 80
      nodePort: 30082
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver2
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: webserver2
  template:
    metadata:
      labels:
        app: webserver2
    spec:
      containers:
        - image: 'maho/webapl2:0.1'
          name: webserver2
          ports:
            - containerPort: 80
---
