- include_vars: /vagrant/playbook/vars/main.yaml
  
- name: Configure CNI Networking
  unarchive:
    src: /mnt/download/cni-plugins-linux-amd64-{{ cni_plugins }}.tgz
    dest: /opt/cni/bin/
    owner: root
    group: root
    mode: '0755'


- name: install containerd
  unarchive:
    src: /mnt/download/containerd-{{ containerd_version }}.linux-amd64.tar.gz
    dest: /usr/local
    owner: root
    group: root
    mode: '0755'

- copy:
    src: /mnt/download/runc.amd64
    dest: /usr/local/bin/runc
    owner: root
    group: root
    mode: '0755'

- name: Configure containerd
  file:
    path: /etc/containerd
    state: directory
    owner: root
    group: root
    mode: '0755'

- template:
    src: config.toml
    dest: /etc/containerd
    owner: root
    group: root
    mode: '0644'

- template:
    src: containerd.service
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: '0644'

- name: Start the Worker Services
  systemd:
    name: containerd  
    state: started
    daemon_reload: yes
    enabled: yes
- wait_for:
    timeout: 30
    
########
- unarchive:
    src: /mnt/download/crictl-{{ crictl_version }}-linux-amd64.tar.gz
    dest: /usr/local/bin
    owner: root
    group: root
    mode: '0755'
########
