## サービス(type NodePort)
apiVersion: v1
kind: Service
metadata:
  name: webserver
spec:
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30080
  type: NodePort
---
## デプロイメント 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: maho/pdtools:1.0
      nodeName: node1
