#
# CRI
#
- name: Downloading cri-containerd
  stat:
    path: "{{ r_download_dir }}/cri-containerd-{{ containerd_version }}.linux-amd64.tar.gz"
  when: ansible_facts.hostname is match(download_node)
  register: regi_cri_containerd

#- debug: msg="{{ cri_containerd }}"

- get_url:
    url: "https://storage.googleapis.com/cri-containerd-release/cri-containerd-{{ containerd_version }}.linux-amd64.tar.gz"
    dest: "{{ r_download_dir }}"
    mode: '0644'
  when:
    - ansible_facts.hostname is match(download_node)
    - regi_cri_containerd.stat.exists == False



