#
# CONTAINERD
#
- name: Downloading containerd
  stat:
    path: "{{ r_download_dir }}/containerd-{{ containerd_version }}.linux-amd64.tar.gz"
  when: ansible_facts.hostname is match(download_node)
  register: regi_containerd

- get_url:
    url: "https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}/containerd-{{ containerd_version }}.linux-amd64.tar.gz"
    dest: "{{ r_download_dir }}"
    mode: '0644'
  when:
    - ansible_facts.hostname is match(download_node)
    - regi_containerd.stat.exists == false


