## サービス(type NodePort)
apiVersion: v1
kind: Service
metadata:
  name: webserver3
spec:
  selector:
    app: webserver3
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30443
  type: NodePort
---
## デプロイメント 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver3
  template:
    metadata:
      labels:
        app: webserver3
    spec:
      containers:
        - name: webserver3
          image: 'maho/webapl2:0.1'

---
## Ingress
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: simple-fanout-webserver
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/affinity: 'cookie'
spec:
  rules:
  - host: k8s.labs.local
    http:
      paths:
      - path: /
        backend:
          serviceName: webserver3
          servicePort: 80
