#- include_vars: /vagrant/playbook/vars/main.yaml
#
# ブリッジ設定でポッドネットワークを構築する
#
- name: deploy /etc/cni/net.d/10-bridge.conf
  template:
    src: "10-bridge.conf.{{ ansible_facts.hostname }}"
    dest: /etc/cni/net.d/10-bridge.conf
    owner: root
    group: root
    mode: '0644'
  when: ansible_facts.hostname is not match("master[123]")

- name: static route masters
  include_tasks: /vagrant/playbook/net_bridge/tasks/static-route.yaml
  when: ansible_facts.hostname is match("master[123]")

  
- name: static route for each node
  include_tasks: "/vagrant/playbook/net_bridge/tasks/static-route-{{ ansible_facts.hostname }}.yaml"
  when: ansible_facts.hostname is not match("master[123]")



