##
## Configure the Kubernetes API Server
##
##
- debug: msg="custom_kubernetes = {{ custom_kubernetes }}"


- name: Configure the Kubernetes API Server
  copy:
    src: "{{ k8s_bin }}/kube-apiserver"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: '0755'
    remote_src: yes

- copy:
    src: "{{ k8s_bin }}/kubectl"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: '0755'
    remote_src: yes

- copy:
    src: "{{ ca_kubeconfig }}/admin.kubeconfig"
    dest: /etc/kubernetes/kube-apiserver.conf
    owner: root
    group: root
    mode: '0644'

- template:
    src: kube-apiserver.service.j2
    dest: /etc/systemd/system/kube-apiserver.service
    owner: root
    group: root
    mode: '0644'
