##
## Configure the Kubernetes API Server
##
##

- name: Configure the Kubernetes API Server
  copy:
    src: /mnt/download/kubernetes/server/bin/kube-apiserver
    dest: /usr/local/bin
    owner: root
    group: root
    mode: '0755'
    remote_src: yes
- copy:
    src: /mnt/download/kubernetes/server/bin/kubectl
    dest: /usr/local/bin
    owner: root
    group: root
    mode: '0755'
    remote_src: yes

- copy:
    src: /mnt/kubeconfig/admin.kubeconfig
    dest: /etc/kubernetes/kube-apiserver.conf
    owner: root
    group: root
    mode: '0644'

- template:
    src: kube-apiserver.service.j2
    dest: /etc/systemd/system/kube-apiserver.service
    owner: root
    group: root
    mode: '0644'
