##
## Containerd のセットアップ
##

- name: setup containerd.conf
  template:
    src: containerd.conf
    dest: /etc/modules-load.d/containerd.conf
    owner: root
    group: root
    mode: '0644'

- apt:
    name: "{{ packages }}"
    state: present
    #update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - libseccomp2

- unarchive:
    src: "{{ r_download_dir }}/cri-containerd-{{ containerd_version }}.linux-amd64.tar.gz"
    dest: /
- file:
    path:  /etc/containerd
    state: directory
    owner: root
    group: root
    mode: '0755'

- shell: containerd config default > /etc/containerd/config.toml

- systemd:
    state: started
    daemon_reload: yes
    name: containerd
    enabled: yes
  when: container_engine == "containerd"
