- name: Copy CA Cert, Server Cert, Client Cert
  copy:
    src: /mnt/ca/ca.pem
    dest: /etc/kubernetes/pki/ca.crt
    owner: root
    group: root
    mode: '0600'
- copy:
    src: /mnt/ca/ca-key.pem  
    dest: /etc/kubernetes/pki/ca.key
    owner: root
    group: root
    mode: '0600'
- copy:
    src: /mnt/ca/kubernetes.pem
    dest: /etc/kubernetes/pki/apiserver.crt
    owner: root
    group: root
    mode: '0600'
- copy:
    src: /mnt/ca/kubernetes-key.pem
    dest: /etc/kubernetes/pki/apiserver.key
    owner: root
    group: root
    mode: '0600'

#-----------------------
- name: Copy ETCD CA Cert
  copy:
    src: /mnt/ca-etcd/etcd-ca.pem
    dest: /etc/kubernetes/pki/etcd/ca.crt
    owner: root
    group: root
    mode: '0600'
- copy:
    src: /mnt/ca/kubernetes.pem
    dest: /etc/kubernetes/pki/apiserver-etcd-client.crt
    owner: root
    group: root
    mode: '0600'
- copy:
    src: /mnt/ca/kubernetes-key.pem
    dest: /etc/kubernetes/pki/apiserver-etcd-client.key
    owner: root
    group: root
    mode: '0600'

#-----------------------
- name: Deploy the apiserver-kubelet-client cert
  copy:
    src: /mnt/ca/kubernetes.pem
    dest: /etc/kubernetes/pki/apiserver-kubelet-client.crt
    owner: root
    group: root
    mode: '0600'
- copy:
    src: /mnt/ca/kubernetes-key.pem
    dest: /etc/kubernetes/pki/apiserver-kubelet-client.key
    owner: root
    group: root
    mode: '0600'
#-----------------------
- name: Deploy the front-proxy-client cert
  copy:
    src: /mnt/ca-front-proxy/front-proxy-client.pem
    dest: /etc/kubernetes/pki/front-proxy-client.crt
    owner: root
    group: root
    mode: '0600'
- copy:
    src: /mnt/ca-front-proxy/front-proxy-client-key.pem
    dest: /etc/kubernetes/pki/front-proxy-client.key
    owner: root
    group: root
    mode: '0600'
- copy:
    src: /mnt/ca-front-proxy/front-proxy-ca.pem
    dest: /etc/kubernetes/pki/front-proxy-ca.crt
    owner: root
    group: root
    mode: '0600'

- name: Deploy service account cert
  copy:
    src: /mnt/ca/service-account.pem
    dest: /etc/kubernetes/pki/service-account.pem
    owner: root
    group: root
    mode: '0600'
- copy:
    src: /mnt/ca/service-account-key.pem
    dest: /etc/kubernetes/pki/service-account.key
    owner: root
    group: root
    mode: '0600'

- name: Deploy encryption-config.yaml
  copy:
    src: /mnt/kubeconfig/encryption-config.yaml
    dest: /var/lib/kubernetes
    owner: root
    group: root
    mode: '0644'
