##
## Configure the Kubernetes Scheduler
##
- name: Copy Scheduler bin
  copy:
    src: /mnt/bin/kube-scheduler
    dest: /usr/local/bin
    owner: root
    group: root
    mode: '0755'
    remote_src: yes


- name: Configure the Kubernetes Scheduler
  copy:
    src: /mnt/kubeconfig/kube-scheduler.kubeconfig
    #dest: /var/lib/kubernetes/
    dest: /etc/kubernetes/kube-scheduler.conf
    owner: root
    group: root
    mode: '0644'
- template:
    src: kube-scheduler.yaml
    dest: /etc/kubernetes/config
    owner: root
    group: root
    mode: '0644'
- template:
    src: kube-scheduler.service.j2
    dest: /etc/systemd/system/kube-scheduler.service
    owner: root
    group: root
    mode: '0644'

