#
# ダウンロード COREDNS
#
- name: Download CoreDNS 
  stat:
    path: "{{ download_dir }}/coredns/README.md"
  register: coredns

- git:
    repo: https://github.com/coredns/deployment
    dest: "{{ download_dir }}/coredns"
    force: yes
    update: yes
  become_user: vagrant    
  when: coredns.stat.exists == false  

