#
# ダウンロード COREDNS
#
- name: Download CoreDNS 
  stat:
    path: "{{ download_dir }}/coredns/README.md"
  register: regi_coredns

- git:
    repo: https://github.com/coredns/deployment
    dest: "{{ download_dir }}/coredns"
    force: yes
    update: yes
  when: regi_coredns.stat.exists == false  

