#
# FLANNEL
#
# この部分は、net_flannelへ入れるべきじゃ？

#- debug: msg="{{ ansible_facts.hostname }}"

- name: Flannel Download 
  stat:
    path: "{{ download_dir }}/flannel-{{ flannel_version }}-linux-amd64.tar.gz"
  register: flannel
  when: flannel_version is defined 

- get_url:
    url: https://github.com/coreos/flannel/releases/download/{{ flannel_version }}/flannel-{{ flannel_version }}-linux-amd64.tar.gz
    dest: "{{ download_dir }}"
    mode: '0644'
  when: flannel_version is defined and flannel.stat.exists == false

- unarchive:
    src:  "{{ download_dir }}/flannel-{{ flannel_version }}-linux-amd64.tar.gz"
    dest: "{{ download_dir }}"
  when: flannel_version is defined 
