#
# KUBERNETES BINARY to NFS export dir on bootnode
#

#
# register: r_k8s_bin の設定と変数が混ざると予想外の動きになる。
#
- name: Downloading Kubernetes binary
  stat:
    path: "{{ download_dir }}/kubernetes-server-linux-amd64.tar.gz"
  register: regi_k8s_bin

- get_url:
    url: https://dl.k8s.io/{{ kubernetes_version }}/kubernetes-server-linux-amd64.tar.gz
    dest: "{{ download_dir }}"
    mode: '0644'
  when: regi_k8s_bin.stat.exists == false and custom_kubernetes == 'false'


- name: Check unarchive 
  stat:
    path: "{{ download_dir }}/kubernetes/server/bin/kube-apiserver"
  register: regi_check_kube_apiserver

  
- unarchive:
    src:  "{{ download_dir }}/kubernetes-server-linux-amd64.tar.gz"
    dest: "{{ download_dir }}"
  when: custom_kubernetes == 'false' and regi_check_kube_apiserver.stat.exists == false

  
- name: Copy kubernetes binary to nfs
  shell: |
    cp -fr {{ download_dir }}/kubernetes/server/bin/* {{ work_dir }}/bin
    chmod -R 0755 {{ work_dir }}/bin
  when: custom_kubernetes == 'false'
  
#
# Copy binary which is builded source 
#
- name: Copy kubernetes binary to nfs
  shell: |
    cp -fr /vagrant/build-k8s/bin/* {{ work_dir }}/bin
    chmod -R 0755 "{{ work_dir }}/bin"
  when: custom_kubernetes == 'true'


