#
# KUBERNETES BINARY to NFS export dir on bootnode
#
- name: Downloading Kubernetes binary
  stat:
    path: "{{ download_dir }}/kubernetes-server-linux-amd64.tar.gz"
  register: k8s_bin

- get_url:
    url: https://dl.k8s.io/{{ kubernetes_version }}/kubernetes-server-linux-amd64.tar.gz
    dest: "{{ download_dir }}"
    mode: '0644'
  when: k8s_bin.stat.exists == false and custom_kubernetes == 'false'

- unarchive:
    src:  "{{ download_dir }}/kubernetes-server-linux-amd64.tar.gz"
    dest: "{{ download_dir }}"
  when: custom_kubernetes == 'false'

- name: Copy kubernetes binary to nfs
  shell: |
    cp -fr {{ download_dir }}/kubernetes/server/bin/* {{ work_dir }}/bin
    chmod -R 0755 {{ work_dir }}/bin
  when: custom_kubernetes == 'false'

  
#
# Copy binary which is builded source 
#
- name: Copy kubernetes binary to nfs
  shell: |
    cp -fr /vagrant/build-k8s/bin/* {{ work_dir }}/bin
    chmod -R 0755 "{{ work_dir }}/bin"
  when: custom_kubernetes == 'true'


