#
# ETCD
#
- name: Downloading etcd
  stat:
    path: /srv/k8s/download/etcd-{{ etcd_version }}-linux-amd64.tar.gz
  register: etcd
- get_url:
    url: https://github.com/etcd-io/etcd/releases/download/{{ etcd_version }}/etcd-{{ etcd_version }}-linux-amd64.tar.gz
    dest: /srv/k8s/download
    mode: '0644'
  when: etcd.stat.exists == false
- unarchive:
    src:  /srv/k8s/download/etcd-{{ etcd_version }}-linux-amd64.tar.gz
    dest: /srv/k8s/download

