#
# FLANNEL
#
- name: Flannel Download 
  stat:
    path: /srv/k8s/download/flannel-{{ flannel_version }}-linux-amd64.tar.gz
  register: flannel
- get_url:
    url: https://github.com/coreos/flannel/releases/download/{{ flannel_version }}/flannel-{{ flannel_version }}-linux-amd64.tar.gz
    dest: /srv/k8s/download
    mode: '0644'
  when: flannel.stat.exists == false	
- unarchive:
    src:  /srv/k8s/download/flannel-{{ flannel_version }}-linux-amd64.tar.gz
    dest: /srv/k8s/download


#
# COREDNS
#
- name: Install coredns from git repo
  git:
    repo: https://github.com/coredns/deployment
    dest: /srv/k8s/download/coredns
    force: yes
    update: yes
  become_user: vagrant    

- name: Downloading keepalived
  stat:
    path: /srv/k8s/download/keepalived-2.0.15.tar.gz
  register: keepalived
- get_url:
    url: https://www.keepalived.org/software/keepalived-2.0.15.tar.gz
    dest: /srv/k8s/download
    mode: '0644'
  when: flannel.stat.exists == false	
- unarchive:
    src:  /srv/k8s/download/keepalived-2.0.15.tar.gz
    dest: /srv/k8s/download

