#
# ブートノードの設定
#
#- debug: msg="{{ ansible_facts.hostname }}"


# ダウンロード用ディレクトリ作成    
- include_tasks: mkdir_for_download.yaml

# ノード設定ツールのインストール
- include_tasks: dl_k8s_bin.yaml
- include_tasks: dl_cfssl.yaml
- include_tasks: install_kubectl.yaml
  
# 共有環境の設定
- include_tasks: start_nfs_server.yaml
- include_tasks: gen-sshkey-root.yaml    

