#
# Download Etcd 
#

- name: Downloading etcd
  stat:
    path: "{{ r_download_dir }}/etcd-{{ etcd_version }}-linux-amd64.tar.gz"
  when: ansible_facts.hostname is match("master1")
  register: regi_etcd
  
- get_url:
    url: https://github.com/etcd-io/etcd/releases/download/{{ etcd_version }}/etcd-{{ etcd_version }}-linux-amd64.tar.gz
    dest: "{{ r_download_dir }}"
    mode: '0644'
  when: ansible_facts.hostname is match("master1") and regi_etcd.stat.exists == false

- unarchive:
    src:  "{{ r_download_dir }}/etcd-{{ etcd_version }}-linux-amd64.tar.gz"
    dest: "{{ r_download_dir }}"
  when: ansible_facts.hostname is match("master1")

##
## master1 でダウンロードが完了したら、master2以降の待機をリリースする
##
- name: Touch the same file, but add/remove some permissions
  file:
    path: "{{ r_download_dir }}/etcd_start.lock"
    state: touch
    mode: u+rw,g-wx,o-rwx  
  when: ansible_facts.hostname is match("master1")
  
##
## master1 でダウンロードが完了するまで待つ
##
- name: Wait until the lock file is removed
  wait_for:
    path: "{{ r_download_dir }}/etcd_start.lock"
    state: present
  when: ansible_facts.hostname is match("master[2-9]")
  
#
# Config Etcd 
#
- name: Setup environment for etcd
  file:
    path: /etc/kubernetes/pki/etcd
    state: directory
    owner: root
    group: root
    mode: '0755'
- file:
    path: /var/lib/etcd
    state: directory
    owner: root
    group: root
    mode: '0755'
- copy:
    src:  "{{ r_download_dir }}/etcd-{{ etcd_version }}-linux-amd64/etcd"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: '0755'
- copy:
    src:  "{{ r_download_dir }}/etcd-{{ etcd_version }}-linux-amd64/etcdctl"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: '0755'
- copy:
    src: "{{ r_ca_home2 }}/ca.pem"
    dest: /etc/kubernetes/pki/ca.crt
    owner: root
    group: root
    mode: '0600'
- copy:
    src: "{{ r_ca_etcd_home }}/etcd-ca.pem"
    dest: /etc/kubernetes/pki/etcd/ca.crt
    owner: root
    group: root
    mode: '0600'
- copy:
    src: "{{ r_ca_etcd_home }}/etcd-ca-key.pem"
    dest: /etc/kubernetes/pki/etcd/ca.key
    owner: root
    group: root
    mode: '0600'
- copy:
    src: "{{ r_ca_etcd_home }}/etcd-server.pem"
    dest: /etc/kubernetes/pki/etcd/server.crt
    owner: root
    group: root
    mode: '0600'
- copy:
    src: "{{ r_ca_etcd_home }}/etcd-server-key.pem"
    dest: /etc/kubernetes/pki/etcd/server.key
    owner: root
    group: root
    mode: '0600'
- copy:
    src: "{{ r_ca_etcd_home }}/etcd-peer.pem"
    dest: /etc/kubernetes/pki/etcd/peer.crt
    owner: root
    group: root
    mode: '0600'
- copy:
    src: "{{ r_ca_etcd_home }}/etcd-peer-key.pem"
    dest: /etc/kubernetes/pki/etcd/peer.key
    owner: root
    group: root
    mode: '0600'

#########    
- name: Copy ETCD CA Cert
  copy:
    src: "{{ r_ca_home2 }}/kubernetes.pem"
    dest: /etc/kubernetes/pki/apiserver-etcd-client.crt
    owner: root
    group: root
    mode: '0600'
- copy:
    src: "{{ r_ca_home2 }}/kubernetes-key.pem"
    dest: /etc/kubernetes/pki/apiserver-etcd-client.key
    owner: root
    group: root
    mode: '0600'
#########    
    
- template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    owner: root
    group: root
    mode: '0644'

- debug: msg="{{ ansible_facts.hostname }}"

- name: Start etcd service
  systemd:
    name: etcd.service
    state: started
    daemon_reload: yes
    enabled: yes

    
