- name: Deploy CoreDNS
  template:
    src: coredns.yaml
    dest: /home/vagrant/coredns.yaml
    owner: vagrant
    group: vagrant
- template:
    src: coredns-configmap.yaml
    dest: /home/vagrant/coredns-configmap.yaml
    owner: vagrant
    group: vagrant

- command: kubectl apply -f coredns-configmap.yaml
  become_user: vagrant
  args:
    chdir: /home/vagrant

- command: kubectl apply -f coredns.yaml
  become_user: vagrant
  args:
    chdir: /home/vagrant
