- name: Deploy CoreDNS
  template:
    src: coredns.yaml
    dest: /home/vagrant/coredns.yaml
    owner: vagrant
    group: vagrant
    mode: 0644

- template:
    src: coredns-configmap.yaml
    dest: /home/vagrant/coredns-configmap.yaml
    owner: vagrant
    group: vagrant
    mode: 0644

- name: kubectl apply -f coredns-configmap.yaml
  shell: |
    kubectl apply -f coredns-configmap.yaml
  become_user: vagrant
  args:
    chdir: /home/vagrant

- name: apply kubectl apply -f coredns.yaml
  shell: |
    kubectl apply -f coredns.yaml
  become_user: vagrant
  args:
    chdir: /home/vagrant
