##
## Install ROOK
##
- name: check rook
  stat:
    path: '/home/vagrant/rook/README.md'
  register: regi_rook

- name: git clone rook
  become_user: "{{ user_name }}"
  git:
    repo: 'https://github.com/rook/rook.git'
    version: release-1.3
    dest: "/home/{{ user_name }}/rook"
  when: regi_rook.stat.exists == false


#
# Rook-Cephインストール ROOK Operator & Ceph Cluster
#
- name: install Rook-Ceph step-3
  become_user: "{{ user_name }}"
  shell: |
    kubectl apply -f common.yaml
    kubectl apply -f operator.yaml
    kubectl apply -f cluster.yaml
  register: results_rook_operator
  args:
    chdir: "/home/{{ user_name }}/rook/cluster/examples/kubernetes/ceph"
- local_action: copy content="{{  results_rook_operator.stdout_lines }}" dest="/home/{{ user_name }}/results_rook_operator"

- wait_for:
    timeout: 300
  
#
# Rook-Cephインストール Dashboard
#
- name: install Rook-Ceph step-4
  become_user: "{{ user_name }}"
  shell: |
    kubectl apply -f dashboard-external-https.yaml
  register: results_rook-ui
  args:
    chdir: "/home/{{ user_name }}/rook/cluster/examples/kubernetes/ceph"
- local_action: copy content="{{  results_rook_ui.stdout_lines }}" dest="/home/{{ user_name }}/results_rook_operator"
