- systemd:
    name: etcd
    state: stopped
    enabled: no
  ignore_errors: yes

- systemd:
    name: flanneld
    state: stopped
    enabled: no
  ignore_errors: yes

- systemd:
    name: containerd
    state: stopped
    enabled: no
  ignore_errors: yes

- systemd:
    name: kube-apiserver
    state: stopped
    enabled: no
  ignore_errors: yes

- systemd:
    name: kube-controller-manager
    state: stopped
    enabled: no
  ignore_errors: yes

- systemd:
    name: kube-scheduler
    state: stopped
    enabled: no
  ignore_errors: yes

- systemd:
    name: kube-proxy
    state: stopped
    enabled: no
  ignore_errors: yes


- file:
    path: /etc/kubernetes
    state: absent
- file:
    path: /etc/etcd
    state: absent
- file:
    path: /var/lib/etcd
    state: absent
- file:
    path: /usr/local/bin/etcd
    state: absent
- file:
    path: /usr/local/bin/etcdctl
    state: absent
- file:    
    path: /etc/systemd/system/etcd.service
    state: absent
- file:    
    path: /etc/systemd/system/kube-apiserver.service
    state: absent
- file:    
    path: /etc/systemd/system/kube-controller-manager.service
    state: absent
- file:    
    path: /etc/systemd/system/kube-scheduler.service
    state: absent


- file:
    path: /var/lib/kubernetes
    state: absent

