- name: Stop the Worker Services
  systemd:
    name: containerd  
    state: stopped
  ignore_errors: yes    

- systemd:
    name: kubelet
    state: stopped
  ignore_errors: yes    
- systemd:
    name: kube-proxy
    state: stopped
  ignore_errors: yes    
- systemd:
    name: flanneld
    state: stopped
  ignore_errors: yes    

- name: clean up files
  file:
    path: /etc/cni/net.d
    state: absent
- file:
    path: /opt/cni/bin
    state: absent
- file:
    path: /var/lib/kubelet
    state: absent
- file:
    path: /var/lib/kube-proxy
    state: absent
- file:
    path: /var/lib/kubernetes
    state: absent
- file:
    path: /var/run/kubernetes
    state: absent
- file:
    path: /etc/systemd/system/containerd.service
    state: absent
- file:
    path: /etc/systemd/system/kubelet.service
    state: absent
- file:
    path: /etc/systemd/system/kube-proxy.service
    state: absent
- file:
    path: /etc/systemd/system/flannel.service
    state: absent

