- name: copy rbac yamls to bootnode
  template:
    src: rbac-kubelet.yaml
    dest: /home/vagrant/rbac-kubelet.yaml
    owner: vagrant
    group: vagrant
    mode: '0644'

- template:
    src: rbac-kubelet-rolebinding.yaml
    dest: /home/vagrant/rbac-kubelet-rolebinding.yaml
    owner: vagrant
    group: vagrant
    mode: '0644'

#- wait_for:
#    timeout: 100

- name: apply rbac manifests
  shell: |
    kubectl apply --kubeconfig {{ ca_kubeconfig }}/admin.kubeconfig -f rbac-kubelet.yaml
  args:
    chdir: /home/vagrant
  become: true

- shell: |
    kubectl apply --kubeconfig {{ ca_kubeconfig }}/admin.kubeconfig -f rbac-kubelet-rolebinding.yaml
  args:
    chdir: /home/vagrant
  become: true


