## kubeconfigディレクトリ作成
#
- name: mkdir kubeconfig
  file:
    path:  "/home/{{ cluster_admin }}/.kube"
    state: directory
    owner: "{{ cluster_admin }}"
    group: "{{ cluster_admin }}"
    mode:  '0755'

- name: copy config to home dir
  copy:
    src:  /etc/kubernetes/kube-apiserver.conf
    dest: "/home/{{ cluster_admin }}/.kube/config"
    remote_src: yes    
    owner: "{{ cluster_admin }}"
    group: "{{ cluster_admin }}"
    mode:  '0600'
  #when: ansible_facts.hostname is match("master[1-9]")
  when: ansible_facts.hostname is match("master*")
  # master一つのシングルノード構成でも動作するように
  
- copy:
    src: "{{ r_ca_kubeconfig }}/admin.kubeconfig"
    dest: "/home/{{ cluster_admin }}/.kube/config"
    remote_src: yes    
    owner: "{{ cluster_admin }}"
    group: "{{ cluster_admin }}"
    mode:  '0600'
  when: ansible_facts.hostname is match("bootnode") or ansible_facts.hostname is match("master")  
  # masterまたはbootnodeの時にコピーされる。 master[123]では動作させない


- copy:
    src: "{{ r_ca_kubeconfig }}/admin.kubeconfig"
    dest: "{{ shared_fs }}/kubeconfig"
    remote_src: yes
    owner: "{{ cluster_admin }}"
    group: "{{ cluster_admin }}"
    mode:  '0600'
  when: ansible_facts.hostname is match("bootnode") or ansible_facts.hostname is match("master")
  # masterまたはbootnodeの時にコピーされる。 master[123]では動作させない
