## kubeconfigディレクトリ作成
#
- name: mkdir kubeconfig
  file:
    path:  /home/vagrant/.kube
    state: directory
    owner: vagrant
    group: vagrant
    mode:  '0755'

- name: copy config to home dir
  copy:
    src:  /etc/kubernetes/kube-apiserver.conf
    dest: /home/vagrant/.kube/config
    remote_src: yes    
    owner: vagrant
    group: vagrant
    mode:  '0600'
  when: ansible_facts.hostname is match("master[1-9]")  
    
- copy:
    src: "{{ ca_kubeconfig }}/admin.kubeconfig"
    dest: /home/vagrant/.kube/config
    remote_src: yes    
    owner: vagrant
    group: vagrant
    mode:  '0600'
  when: ansible_facts.hostname is match("bootnode")  

- copy:
    src: "{{ ca_kubeconfig }}/admin.kubeconfig"
    dest: /vagrant/kubeconfig
    remote_src: yes    
    owner: vagrant
    group: vagrant
    mode:  '0600'
  when: ansible_facts.hostname is match("bootnode") or ansible_facts.hostname is match("master")

