#
# メトリックスサーバーのデプロイ用 (Brigde, Flannelで動作)
#
- name: Install Metrics Server
  get_url:
    url: "https://github.com/kubernetes-sigs/metrics-server/releases/download/{{ kubernetes_metrics_server }}/components.yaml"
    dest: "{{ download_dir }}"
    mode: '0644'
  become_user: vagrant    

- name: add a new line
  blockinfile:
    path: "{{ download_dir }}/components.yaml"
    insertafter: '        args:'
    block: |
           # added lines
                     - --kubelet-insecure-tls
                     - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
  become_user: vagrant

- name: Deploy Metrics Server
  command: kubectl apply -f {{ download_dir }}/components.yaml
  become_user: vagrant
  args:
    chdir: /home/vagrant
  become_user: vagrant
