# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "16384"
     vb.cpus = 16
  end
  config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y build-essential docker.io
     usermod -aG docker vagrant
     export GO_VER="1.14.2"
     curl -s -O https://dl.google.com/go/go${GO_VER}.linux-amd64.tar.gz
     tar -C /usr/local -xzf go${GO_VER}.linux-amd64.tar.gz
     echo "export PATH=$PATH:/usr/local/go/bin" > /home/vagrant/.profile
     echo "export GOPATH=/home/vagrant" >> /home/vagrant/.profile
  SHELL
end

