#
# ETCD認証局
#

- name: Create ETCD CA working directory
  file:
    path: "{{ ca_etcd_home }}"
    state: directory
    owner: vagrant
    group: vagrant

#
# ETCD CAの作成
#
- name: Create Etcd CA
  template:  
    src: etcd-ca-config.json
    dest: "{{ ca_etcd_home }}"
    owner: vagrant
    group: vagrant
    mode: '0644'
- template:
    src: etcd-ca-csr.json
    dest: "{{ ca_etcd_home }}"
    owner: vagrant
    group: vagrant
    mode: '0644'
- shell: |
    cfssl gencert -initca etcd-ca-csr.json | cfssljson -bare etcd-ca
  args:
    chdir: "{{ ca_etcd_home }}"


#
# ETCD サーバー証明書
#
- name: ETCD Server Certificate
  template:
    src: etcd-csr.json
    dest: "{{ ca_etcd_home }}"
    owner: vagrant
    group: vagrant
    mode: '0644'
- shell: |
    cfssl gencert \
      -ca=etcd-ca.pem \
      -ca-key=etcd-ca-key.pem \
      -config=etcd-ca-config.json \
      -hostname={{ host_list_etcd }} \
      -profile=kubernetes \      
    etcd-csr.json | cfssljson -bare etcd-server
  args:
    chdir: "{{ ca_etcd_home }}"

#
# ETCD ピア証明書
#
- name: ETCD Peer Certificate
  template:
    src: etcd-peer-csr.json
    dest: "{{ ca_etcd_home }}"
    owner: vagrant
    group: vagrant
    mode: '0644'
- shell: |
    cfssl gencert \
      -ca=etcd-ca.pem \
      -ca-key=etcd-ca-key.pem \
      -config=etcd-ca-config.json \
      -hostname={{ host_list_etcd }} \      
      -profile=kubernetes \
    etcd-peer-csr.json | cfssljson -bare etcd-peer
  args:
    chdir: "{{ ca_etcd_home }}"









