- name: Create Kubernetes CA working directory
  file:
    path: "{{ ca_home }}"
    state: directory
    owner: vagrant
    group: vagrant

#
# Kubernetes CAの作成
#
- name: Create CA
  template:  
    src: ca-config.json
    dest: "{{ ca_home }}"
    owner: vagrant
    group: vagrant
    mode: '0644'
- template:
    src: ca-csr.json
    dest: "{{ ca_home }}"
    owner: vagrant
    group: vagrant
    mode: '0644'
- shell: |
    cfssl gencert -initca ca-csr.json | cfssljson -bare ca
  args:
    chdir: "{{ ca_home }}"

#
# kubectl の管理者用クライアント証明書
# 　The Admin Client Certificate
#
- name: Admin Client Certificate
  template:
    src: admin-csr.json
    dest: "{{ ca_home }}"
    owner: vagrant
    group: vagrant
    mode: '0644'
- shell: |
    cfssl gencert \
      -ca=ca.pem \
      -ca-key=ca-key.pem \
      -config=ca-config.json \
      -profile=kubernetes \
    admin-csr.json | cfssljson -bare admin
  args:
    chdir: "{{ ca_home }}"

#
# Kubeletのクライアント証明書
#    The Kubelet Client Certificates
#    ノードの数だけ作成する
#
#- name: Kubelet Client Certificates
#  template:
#    src: instance-csr.json.j2
#    dest: ""{{ ca_home }}"/{{ item.name }}-csr.json"
#    owner: vagrant
#    group: vagrant
#    mode: '0644'
#  loop: "{{ nodes }}"
#- shell: |
#    cfssl gencert \
#      -ca=ca.pem \
#      -ca-key=ca-key.pem \
#      -config=ca-config.json \
#      -hostname="{{ item.name }},{{ item.pri_ip }}" \
#      -profile=kubernetes \
#      "{{ item.name }}-csr.json" | cfssljson -bare "{{ item.name }}"
#  args:
#    chdir: "{{ ca_home }}"
#  loop: "{{ nodes }}"
#- file:
#    path: ""{{ ca_home }}"/{{ item.name }}-key.pem"
#    mode: '0644'
#  loop: "{{ nodes }}"



# 
# Controller-Manager のクライアント証明書
#   The Controller Manager Client Certificate
#
- name: Controller Manager Client Certificate
  template:
    src: kube-controller-manager-csr.json
    dest: "{{ ca_home }}"
    owner: vagrant
    group: vagrant
    mode: '0644'
- shell: |
    cfssl gencert \
      -ca=ca.pem \
      -ca-key=ca-key.pem \
      -config=ca-config.json \
      -profile=kubernetes \
    kube-controller-manager-csr.json | cfssljson -bare kube-controller-manager    
  args:
    chdir: "{{ ca_home }}"



#
# Kubeプロキシのクライアント証明書
#   The Kube Proxy Client Certificate
#
- name: Kube Proxy Client Certificate
  template:
    src: kube-proxy-csr.json
    dest: "{{ ca_home }}"
    owner: vagrant
    group: vagrant
    mode: '0644'
- shell: |
    cfssl gencert \
      -ca=ca.pem \
      -ca-key=ca-key.pem \
      -config=ca-config.json \
      -profile=kubernetes \
    kube-proxy-csr.json | cfssljson -bare kube-proxy
  args:
    chdir: "{{ ca_home }}"


# 
# スケジューラーのクライアント証明書
#   The Scheduler Client Certificate
#
- name: Scheduler Client Certificate
  template:
    src: kube-scheduler-csr.json
    dest: "{{ ca_home }}"
    owner: vagrant
    group: vagrant
    mode: '0644'
- shell: |
    cfssl gencert \
      -ca=ca.pem \
      -ca-key=ca-key.pem \
      -config=ca-config.json \
      -profile=kubernetes \
    kube-scheduler-csr.json | cfssljson -bare kube-scheduler
  args:
    chdir: "{{ ca_home }}"

#
# APIサーバーのサーバー証明書
#   The Kubernetes API Server Certificate
#
- name: Kubernetes API Server Certificate
  template:
    src: kubernetes-csr.json
    dest: "{{ ca_home }}"
    owner: vagrant
    group: vagrant
    mode: '0644'
- shell: |
    cfssl gencert \
      -ca=ca.pem \
      -ca-key=ca-key.pem \
      -config=ca-config.json \
      -hostname={{ host_list_k8sapi }} \
      -profile=kubernetes \
    kubernetes-csr.json | cfssljson -bare kubernetes
  args:
    chdir: "{{ ca_home }}"

#
# サービスアカウントの公開鍵ペア
#   The Service Account Key Pair
#
- name: Service Account Key Pair
  template:
    src: service-account-csr.json
    dest: "{{ ca_home }}"
    owner: vagrant
    group: vagrant
    mode: '0644'
- shell: |
    cfssl gencert \
      -ca=ca.pem \
      -ca-key=ca-key.pem \
      -config=ca-config.json \
      -hostname={{ host_list_k8sapi }} \
      -profile=kubernetes \
     service-account-csr.json | cfssljson -bare service-account
  args:
    chdir: "{{ ca_home }}"


