#
# Kubeletのクライアント証明書
#    The Kubelet Client Certificates
#    ノードの数だけ作成する
#
- name: Kubelet Client Certificates
  template:
    src: instance-csr.json.j2
    dest: "/srv/k8s/ca/{{ item.name }}-csr.json"
    owner: vagrant
    group: vagrant
    mode: '0644'
  loop: "{{ nodes }}"
- shell: |
    if [ ! -f "{{ item.name }}.pem" ]; then
      cfssl gencert \
        -ca=ca.pem \
        -ca-key=ca-key.pem \
        -config=ca-config.json \
        -hostname="{{ item.name }},{{ item.pri_ip }}" \
        -profile=kubernetes \
        "{{ item.name }}-csr.json" | cfssljson -bare "{{ item.name }}"
    fi
  args:
    chdir: /srv/k8s/ca
    executable: /bin/bash    
  loop: "{{ nodes }}"
- file:
    path: "/srv/k8s/ca/{{ item.name }}-key.pem"
    mode: '0644'
  loop: "{{ nodes }}"


#
# kubelet Kubernetes Configuration File
#
- name: Ensure kubeconfig Home directory
  file:
    path: /srv/k8s/kubeconfig
    state: directory
    owner: vagrant
    group: vagrant

- shell: |
    if [ ! -f "{{ item.name }}.kubeconfig" ]; then    
      kubectl config set-cluster kubernetes \
        --certificate-authority=ca.pem \
        --embed-certs=true \
        --server=https://{{ KUBERNETES_PUBLIC_ADDRESS }}:6443 \
        --kubeconfig=/srv/k8s/kubeconfig/{{ item.name }}.kubeconfig

      kubectl config set-credentials system:node:{{ item.name }} \
        --client-certificate={{ item.name }}.pem \
        --client-key={{ item.name }}-key.pem \
        --embed-certs=true \
        --kubeconfig=/srv/k8s/kubeconfig/{{ item.name }}.kubeconfig

      kubectl config set-context default \
        --cluster=kubernetes \
        --user=system:node:{{ item.name }} \
        --kubeconfig=/srv/k8s/kubeconfig/{{ item.name }}.kubeconfig

      kubectl config use-context default --kubeconfig=/srv/k8s/kubeconfig/{{ item.name }}.kubeconfig
    fi
  args:
    chdir: /srv/k8s/ca
    executable: /bin/bash    
  loop: "{{ nodes }}"

- file:
    path: "/srv/k8s/kubeconfig/{{ item.name }}.kubeconfig"
    mode: '0644'
  loop: "{{ nodes }}"
  
