#
# Knative のデプロイ
#
#- debug: msg="{{ ansible_facts.hostname }}"

- git:
    repo: https://github.com/knative/serving
    dest: "/home/{{ user_name }}/knative_serving"
    version: v0.17.2
  become_user: "{{ user_name }}"

- git:
    repo: https://github.com/knative/eventing
    dest: "/home/{{ user_name }}/knative_eventing"
    version: v0.17.3
  become_user: "{{ user_name }}"

  
