- debug: msg="{{ ansible_facts.hostname }}"

- name: Download Nginx Ingress Controller Manifest
  get_url:
    url: "https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-{{ nginx_ic_version }}/deploy/static/provider/baremetal/deploy.yaml"
    dest: "/home/{{ user_name }}/ingress-controller-nginx.yaml"
    mode: '0644'
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

  
