- debug: msg="{{ ansible_facts.hostname }}"

- name: check istio
  stat:
    path: "/home/{{ cluster_admin }}/istio-{{ istio_version }}/README.md"
  register: file_istio

#
# Istio のインストール
#
- name: install Istio step-1
  become_user: "{{ cluster_admin }}"
  shell: |
    curl -L https://istio.io/downloadIstio | ISTIO_VERSION={{ istio_version }} TARGET_ARCH=x86_64 sh -
  args:
    chdir: "/home/{{ cluster_admin }}"
  when: file_istio.stat.exists == False


- name: install Istio step-2
  become_user: "{{ cluster_admin }}"
  shell: |
    export PATH=$PWD/bin:$PATH
    istioctl install --set profile=default
  args:
    chdir: "/home/{{ cluster_admin }}/istio-{{ istio_version }}"

#
# Istio パッチを適用する、NodePortとして公開するため。
#
- template:
    src: istio-patch.yaml
    dest: "/home/{{ cluster_admin }}/istio-patch.yaml"
    owner: "{{ cluster_admin }}"
    group: "{{ cluster_admin }}"
    mode: '0644'
    
- name: apply patch for Istio
  become_user: "{{ cluster_admin }}"
  shell: |
    kubectl patch svc istio-ingressgateway --patch "$(cat istio-patch.yaml)" -n istio-system
  args:
    chdir: "/home/{{ cluster_admin }}"

#
# istioctl は bootnode の /usr/local/bin へ配置する
#
- name: deploy istioctl to /usr/local/bin
  copy:
    src: "/home/{{ cluster_admin }}/istio-{{ istio_version }}/bin/istioctl"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: '0755'


##
## Kiali, Jeager のインストールと公開
## 

- name: apply patch for Istio
  become_user: "{{ cluster_admin }}"
  shell: |
    kubectl apply -f prometheus.yaml
    kubectl apply -f grafana.yaml
    kubectl apply -f jaeger.yaml
    kubectl apply -f kiali.yaml
    kubectl patch svc kiali -n istio-system -p '{"spec":{"type":"NodePort","ports":[{"name": "http","port": 20001,"nodePort": 32001},{"port":9090, "nodePort":32090}]}}'
    kubectl patch svc tracing -n istio-system -p '{"spec":{"type":"NodePort","ports":[{"name": "http","port": 80,"nodePort": 32095}]}}'
  args:
    chdir: "/home/{{ cluster_admin }}/istio-{{ istio_version }}/samples/addons/"


    
    
  
