- include_vars: /vagrant/playbook/vars/main.yaml

- name: start configuration  
  file:
    path: /etc/cni/net.d
    state: directory
    owner: root
    group: root
    mode: '0755'
- file:
    path: /opt/cni/bin
    state: directory
    owner: root
    group: root
    mode: '0755'


