#- include_vars: /vagrant/playbook/vars/main.yaml

- name: copy calico-custom.yaml to local
  template:
    src: calico-custom.yaml
    dest: "/home/{{ cluster_admin }}/calico-custom.yaml"
    owner: "{{ cluster_admin }}"
    group: "{{ cluster_admin }}"
    mode: '0644'

    
- name: deploy calico by kubectl
  shell: |
    kubectl apply -f calico-custom.yaml
  args:
    chdir: "/home/{{ cluster_admin }}"
  when: ansible_facts.hostname is match("bootnode")
  become: true
  become_user: "{{ cluster_admin }}"


- name: Download calicoctl command
  get_url:
    url: "https://github.com/projectcalico/calicoctl/releases/download/{{ calico_version }}/calicoctl"
    dest: /usr/local/bin/calicoctl
    mode: '0755'
    owner: root
    group: root
  when: ansible_facts.hostname is match("bootnode") or ansible_facts.hostname is match("master*")

  
- name: setup ENVIRONMENT VAR in .profile at home dir
  shell: |
    cat <<EOF >> /home/{{ cluster_admin }}/.profile
    # for calicoctl
    export DATASTORE_TYPE=kubernetes
    export KUBECONFIG=~/.kube/config

  args:
    chdir: "/home/{{ cluster_admin }}"
  when: ansible_facts.hostname is match("bootnode") or ansible_facts.hostname is match("master*")

