#
#
#

### host network interfaice
#bridge_if: "en0: Wi-Fi (Wireless)"
bridge_if: "eno1"

### Kubernetes version
kubernetes_version: 1.18.2
#kubernetes_version: 1.17.5
#kubernetes_version: 1.16.8

### K8s cluster/pod network CNI plugin
pod_network: bridge
#pod_network: flannel

### flannel_version if you choice flannel
flannel_version: v0.12.0

### Cluster Network
kube_apiserver_ip: mlb1
private_ip_subnet: 172.16.2.0/24
public_ip_subnet:  192.168.1.0/24


### Virtual Machine Spec
vm_spec:
  - name: "bootnode"
    cpu: 1
    memory: 1024
    private_ip: "172.16.2.3"
    comment: "Bootstap node" 

  - name: "master1"
    cpu: 2
    memory: 2048
    box: "ubuntu/bionic64"
    private_ip: "172.16.2.4"
    storage:
    playbook: "setup_linux.yml"
    comment: "Master node #1"
    
  - name: "master2"
    cpu: 2
    memory: 2048
    box: "ubuntu/bionic64"
    private_ip: "172.16.2.5"
    storage:
    playbook: "setup_linux.yml"
    comment: "Master node #2"
    
  - name: "master3"
    cpu: 2
    memory: 2048
    box: "ubuntu/bionic64"
    private_ip: "172.16.2.6"
    storage:
    playbook: "setup_linux.yml"
    comment: "Master node #3"
  
  - name: "mlb1"
    cpu: 1
    memory: 1024
    box: "ubuntu/bionic64"
    private_ip: "172.16.2.7"
    storage:
    playbook: "setup_linux.yml"
    comment: "Master Loadbalancer #1"

  - name: "node1"
    cpu: 1
    memory: 1024
    box: "ubuntu/bionic64"
    private_ip: "172.16.2.8"
    public_ip: "192.168.1.55"
    storage:
    playbook: "setup_linux.yml"
    pod_network: "10.244.1.0/24"
    role: "worker"
    comment:  "Worker node #1"

  - name: "node2"
    cpu: 1
    memory: 1024
    box: "ubuntu/bionic64"
    private_ip: "172.16.2.9"
    public_ip: "192.168.1.56"
    storage:
    playbook: "setup_linux.yml"
    pod_network: "10.244.2.0/24"
    role: "worker"
    comment:  "Worker node #2"
